name = "Groth"
uuid = "e34f7f6a-9c7d-4ec3-a9f1-96c8f2b5c8d1"
authors = ["Franco <franco@example.com>"]
version = "0.1.0"

[deps]
GrothAlgebra = "c7a79d44-cfd6-4e24-8a20-28d2d2e8370b"
GrothCrypto = "08fad72d-3c18-4088-bc06-6cd170572595"
GrothCurves = "5abac9ed-d1ba-4f09-bf87-1d0505e406bb"
GrothProofs = "a08a9250-f3dc-4127-bcf9-3e12d47ce125"
GrothExamples = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

[workspace]
members = ["GrothAlgebra", "GrothCrypto", "GrothCurves", "GrothProofs", "GrothExamples"]